### ISSUE TITLE
RMarkdown knitting failing

### ISSUE THREAD

**Issue by shoummashams** [espm-157/final-project-shoumma-and-leah#2]
Libraries will not load when knitting. Initially this was an issue of specifying a mirror for the libraries which was resolved by including a setup chunk, but now an error that the library does not exist gets thrown.

**Comment by arothste24** [comment]
Can you copy and paste the error itself?  Or screenshot?

**Comment by shoummashams** [comment]
![image](https://user-images.githubusercontent.com/17078281/49907199-0756a300-fe2a-11e8-926b-b3f705115dba.png)

**Comment by arothste24** [comment]
OK - I'm pulling down your code and trying to kint it on my computer.  Standby...

**Comment by arothste24** [comment]
OK it knits fine on my side.  I pushed a version simply removing the installs of each package.  Once you've done that you shouldn't have to do it again and it probably was why it was asking for mirrors/library problems.  Please pull this new version of the .Rmd and see if this works on your computer

**Comment by shoummashams** [comment]
The issue is that Travis didn't work without us including the installs as well, so I guess we'll see how that goes, it's running right now.

**Comment by arothste24** [comment]
Travis passed.

**Comment by shoummashams** [comment]
Oh it passed, guess that the mirror specifying part might have been the only thing needed in the beginning. Thanks for the help

**Comment by shoummashams** [comment]
Hmmm, I'm still getting an error for that chunk but this time it's just blank. Might be an environment issue?

**Comment by arothste24** [comment]
OK - this time just give me a screenshot of your entire RStudio with the error in it so I can try to assess it

**Comment by shoummashams** [comment]
![image](https://user-images.githubusercontent.com/17078281/49908554-fb6ddf80-fe2f-11e8-83e7-23f42d7df102.png)

**Comment by arothste24** [comment]
Hmm I guess that's not as informative to me if I can't recreate the error.  Two things:

1) Can you restart RStudio and see if you can knit a previous module?  making sure knitr is working on your end
2) can @leahrosemariej pull down the most recent version and knit on her computer?

**Comment by arothste24** [comment]
If nothing works and there is no informative errors, let me know when you have a final version of your .Rmd and I will knit on my computer to push your .md for you.

**Comment by shoummashams** [comment]
![image](https://user-images.githubusercontent.com/17078281/49908986-d24e4e80-fe31-11e8-842d-488fcec152d8.png)
This is where the execution halted. I'll try knit another assignment

**Comment by shoummashams** [comment]
I'll try update my R packages and see if that helps, not sure why the sf package is causing issues.

**Comment by arothste24** [comment]
Try to install mapview and sf in your console directly with dependencies = TRUE.  
e.g.
install.packages("sf", dependencies = TRUE)
install.packages("mapview", dependencies = TRUE)
